# https://fabricmc.net/develop

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# org.gradle.java.home=C:\\Program Files\\Java\\jdk-25
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
minecraft_dependency=~26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
target_java_version=25
# Mod Properties
mod_id=apostlesbridgenext
mod_version=1.11.10-patch.1
maven_group=com.medua
archives_base_name=ApostlesBridgeNext
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.158.0+26.2
fabric_dependency=fabric-api
# Moulconfig
moulconfig_version=26.2:4.7.2
